### Particle Image Function
### Version: 1.0.4
### Width: 32
### Height: 32
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

# say "halo"